### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by anoomolu** [JerryLu086/Netherite-Horse-Armor#1]
Hiya! Love the sprite and textures of your netherite horse armour btw, I had two questions about the mod itself:
- How many points of armour does it give? On the wiki, leather gives 3 while diamond gives 11, for example.
- Does having NHA give the horse any protection from lava like normal netherite armour?

Thanks once again for this small but lovely mod ^^

**Comment by JerryLu086** [comment]
For the questions:

1. It gives 13 (like another old and popular one did)
2. Actually Netherite Armor in vanilla doesn't grant you lava protection. It's just too strong that you might thought you take less damage specific from fire damage sources, but actually no. The same goes with the Horse Armor.

I think that's all? Thanks for the compliments by the way. Of course, you can have more questions here if you want!

**Comment by matzar24** [comment]
Is it compatible with Shiny Horses? Enchants...
