### ISSUE TITLE
Doesn't work with better animation

### ISSUE THREAD

**Issue by joao-carmassi** [JerryLu086/Netherite-Horse-Armor#2]
![2024-04-25_23 00 19](https://github.com/JerryLu086/Netherite-Horse-Armor/assets/90992816/7521a4dd-5d33-46b0-93c0-d099ae0e2997)

**Comment by JerryLu086** [comment]
https://modrinth.com/resourcepack/better-animations
This one? I've found many things called Better Animation and such when I searched  for it. Also, what launcher and which MC version? Thanks.

**Comment by JerryLu086** [comment]
Well, I'll close this for now, since there's no further update on this issue.
