### ISSUE TITLE
[Suggestion] Trimmable Netherite Horse Armor?

### ISSUE THREAD

**Issue by Fyoncle** [JerryLu086/Netherite-Horse-Armor#3]
Wouldn't it look crazy >;)

**Comment by JerryLu086** [comment]
Ahhh sorry I haven't checked GitHub for quite a while until now. 

Well, Vanilla does not have this feature, while I only wanted to make this a simple mod, so no, it wouldn't be added. If you have any mod that has this feature, it should theoretically work. Thanks for the suggestion though.
